bankia-website:
  image: jantoniucci/bankia-website
  ports: 
    - "8080:80"
  labels:
    io.rancher.container.hostname_override: container_name

kopf:
  image: rancher/kopf:v0.4.0
  ports: 
    - "80:80"
  environment:
    KOPF_SERVER_NAME: 'website'
    KOPF_ES_SERVERS: 'website:8080'
  labels:
    io.rancher.container.hostname_override: container_name
  links:
    - bankia-website:website
