bankia-website:
  image: jantoniucci/bankia-website
  ports: 
    - "8080:80"
  labels:
    io.rancher.container.hostname_override: container_name

haproxy:
  image: tutum/haproxy
  ports: 
    - "80:80"
  links:
    - bankia-website:website
  environment:
    - BACKEND_PORT=8080
